name = "dedirock-keep-live"
main = "src/worker.js"
compatibility_date = "2026-05-03"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "CONFIG"
id = "replace_with_your_kv_namespace_id"
